# Generated by Django 6.0.4 on 2026-04-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_id', models.CharField(help_text='The _id from KoboToolbox', max_length=255, unique=True)),
                ('family_member_count', models.IntegerField(help_text='How many members are there in your family?')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submission time from KoboToolbox', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When we received the webhook')),
            ],
            options={
                'verbose_name': 'Census Submission',
                'verbose_name_plural': 'Census Submissions',
                'db_table': 'census_submission',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is your name?', max_length=200)),
                ('contact_number', models.CharField(help_text='Your contact number', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='What is your Gender?', max_length=20)),
                ('age', models.IntegerField(help_text='Enter your age')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core_data.censussubmission')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'family_member',
                'ordering': ['name'],
            },
        ),
    ]
