# Generated by Django 6.0.4 on 2026-04-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0002_censussubmission_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'user_details',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='submission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='CensusSubmission',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
