# Generated by Django 6.0.4 on 2026-04-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0003_user_details_remove_familymember_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
