# Generated by Django 6.0.4 on 2026-04-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_response_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response_table',
            options={'ordering': ['-id'], 'verbose_name': 'Response Table', 'verbose_name_plural': 'Response Tables'},
        ),
        migrations.AlterModelTable(
            name='response_table',
            table='response_table',
        ),
    ]
