# Generated by Django 5.2.6 on 2026-04-27 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0006_new_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stu_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('parents_name', models.CharField(max_length=200)),
                ('batch', models.DateField(verbose_name='')),
                ('faculty', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Student_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('fee_amount', models.IntegerField()),
                ('payed_amount', models.IntegerField()),
                ('due_amount', models.IntegerField()),
                ('pay_date', models.DateField(verbose_name='')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.student')),
            ],
            options={
                'verbose_name': 'Student_fee',
                'verbose_name_plural': 'Student_fees',
            },
        ),
    ]
