# Generated by Django 5.2.6 on 2026-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_student_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.DateField(verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student_fee',
            name='pay_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
    ]
